ktor:
  deployment:
    port: 8080
    rootPath: '/api'
serverUrl:
  - 'https://youthwrite.com'
  - "/api"
  - "/"
database:
  # 数据库实现, 可选值: sql, memory
  impl: sql
  sql: # 该配置项仅在 impl 为 sql 时必须, 其余情况下无效

    # 支持的数据库：
    # - Postgres

    #数据库用户名
    user: 'YourSqlUser'
    #数据库密码
    password: 'YourSqlPassword'

    # 数据库连接地址
    url: 'jdbc:postgresql://YourSqlHost:YourSqlPort/YourDatabaseName' # postgres

    # 数据库驱动 该项可以不填或填为null以通过url自动识别对应驱动
    driver: null
    # 目前支持的数据库驱动有:
    ## driver: 'org.postgresql.Driver' # postgres

    # 数据库懒惰初始化
    lazyInit: true